research_task:
  description: >
    Conduct thorough research on the stock for {topic}. This includes analyzing its historical performance, industry trends,
    and any significant events or market sentiment affecting the stock. Pay close attention to recent news, press releases,
    and industry analysis. Include a summary of potential impacts from upcoming events like earnings or announcements.

  expected_output: >
    Provide a detailed research report that includes:
    - 1 bulletpoints of the stock's recent news and performance.
    Make sure to use the most recent data available.
  agent: researcher

accounting_task:
  description: >
    Perform a detailed financial analysis of {topic} by calculating key accounting ratios such as P/E ratio, EPS growth,
    current ratio, quick ratio, and debt-to-equity ratio. Use the company's latest financial statements and compare these metrics
    with industry standards and competitors.

  expected_output: >
    A comprehensive financial analysis report that includes:
    - A list of all calculated ratios.
    - An interpretation of what these ratios indicate about the company's financial health.
    The report should be well-structured and easy to interpret.
  agent: accountant

recommending_task:
  description: >
    Take the findings from the Accountant to create a detailed investment recommendation for {topic}.
    Incorporate insights from research, accounting ratios, and any qualitative factors like market sentiment or industry trends.
    Provide a clear buy, sell, or hold recommendation with a supporting rationale.

  expected_output: >
    A simple investment recommendation report that includes:
    - A clear buy, sell, or hold recommendation.
    Ensure the report is professionally formatted and easy to read.
  agent: recommender

blogging_task:
  description: >
    Take the findings from the Recommender to create a well-formatted and simple blog post
    about {topic}. The post should summarize the key points in an accessible way, including the investment recommendation,
    and highlight the most compelling insights.

  expected_output: >
    A simple blog post that includes:
    - A one line description of the stock.
    - A clear buy, sell, or hold recommendation.
    Ensure that it is simple enough for general readers to understand.
  agent: blogger